{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-core",
    "version": "6.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-crypto",
          "version": {
            "requires": "6.5.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-core-6.5.7.jar",
          "url": "spring-security-core-6.5.7.jar",
          "size": 622844,
          "sha512": "ab825d4703cc056055dcdce510db914f1454649a0a91cc481e7f4e597ce88429f9e6f8c60adf7f9536bdae9bf56bdc57b8f72acda0d155336ccbdb08f81bae03",
          "sha256": "df44f29203d329f23ff166f203261ad82eada9ba2bce6a7b9a7bac125a424d0a",
          "sha1": "a0c9068ed82f0ddf21231cc7c7dd4bd6b2ef4029",
          "md5": "fa3ae54aa9254786851e83afeb1ecfc6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-crypto",
          "version": {
            "requires": "6.5.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-core-6.5.7.jar",
          "url": "spring-security-core-6.5.7.jar",
          "size": 622844,
          "sha512": "ab825d4703cc056055dcdce510db914f1454649a0a91cc481e7f4e597ce88429f9e6f8c60adf7f9536bdae9bf56bdc57b8f72acda0d155336ccbdb08f81bae03",
          "sha256": "df44f29203d329f23ff166f203261ad82eada9ba2bce6a7b9a7bac125a424d0a",
          "sha1": "a0c9068ed82f0ddf21231cc7c7dd4bd6b2ef4029",
          "md5": "fa3ae54aa9254786851e83afeb1ecfc6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-core-6.5.7-javadoc.jar",
          "url": "spring-security-core-6.5.7-javadoc.jar",
          "size": 1455100,
          "sha512": "65946a0b116857e95be8d4013124c74f577ea612bd04070d468c6c9862d5902be39dbcb1e9ea8030dbfff460f1a60507a9007522a17f730ec4f859f9bc85490d",
          "sha256": "c33c4ad9486fa6f06c3c80568f276f0c8c85c1dc76b318ed40c110297d697c3e",
          "sha1": "0108dae40385897406e47711944c4104654d978d",
          "md5": "6434f2ed5e4254329b85d37e9e2a8242"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-core-6.5.7-sources.jar",
          "url": "spring-security-core-6.5.7-sources.jar",
          "size": 589296,
          "sha512": "bb24af11b8c18bf55de2e7192876e5e5315c8b19b413647d5ba5a408f47f8acc78555cdd73520d8f330922c10f4448a4ea6caf6a3010b5d917eca88d1e038720",
          "sha256": "7007809d661f0732bbe39744625809d5d61347b0188da7e3cea38a830e104f6c",
          "sha1": "c67a8132a30f7d173f4928ebc755f08c5f2797f5",
          "md5": "def14ed951c98f97fb455c3ee2c63e4d"
        },
        {
          "name": "spring-security-core-6.5.7-sources.jar",
          "url": "spring-security-core-6.5.7-sources.jar",
          "size": 589296,
          "sha512": "bb24af11b8c18bf55de2e7192876e5e5315c8b19b413647d5ba5a408f47f8acc78555cdd73520d8f330922c10f4448a4ea6caf6a3010b5d917eca88d1e038720",
          "sha256": "7007809d661f0732bbe39744625809d5d61347b0188da7e3cea38a830e104f6c",
          "sha1": "c67a8132a30f7d173f4928ebc755f08c5f2797f5",
          "md5": "def14ed951c98f97fb455c3ee2c63e4d"
        }
      ]
    }
  ]
}
