{
  "formatVersion": "1.1",
  "component": {
    "group": "nz.net.ultraq.thymeleaf",
    "module": "thymeleaf-layout-dialect",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.25"
          }
        }
      ],
      "files": [
        {
          "name": "thymeleaf-layout-dialect-3.4.0.jar",
          "url": "thymeleaf-layout-dialect-3.4.0.jar",
          "size": 173546,
          "sha512": "b7e7215af65996477ffc42f20f4a27628657de67dae73a1d123539ebb8282d7ff3b965aa59be0bbeca277f6f9588226dbffef90216858200ed2072a62bc73e0a",
          "sha256": "b4bbd98b81d2ffcfd62b6b028d76192085eea86d83e7c73947ec54a8079cc351",
          "sha1": "44360e674eb9762f33db69e46612bccdc39ec281",
          "md5": "637f95da5f1174e05277999cb466a094"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "nz.net.ultraq.groovy",
          "module": "groovy-extensions",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "nz.net.ultraq.thymeleaf",
          "module": "thymeleaf-expression-processor",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf",
          "version": {
            "requires": "3.1.3.RELEASE"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.25"
          }
        }
      ],
      "files": [
        {
          "name": "thymeleaf-layout-dialect-3.4.0.jar",
          "url": "thymeleaf-layout-dialect-3.4.0.jar",
          "size": 173546,
          "sha512": "b7e7215af65996477ffc42f20f4a27628657de67dae73a1d123539ebb8282d7ff3b965aa59be0bbeca277f6f9588226dbffef90216858200ed2072a62bc73e0a",
          "sha256": "b4bbd98b81d2ffcfd62b6b028d76192085eea86d83e7c73947ec54a8079cc351",
          "sha1": "44360e674eb9762f33db69e46612bccdc39ec281",
          "md5": "637f95da5f1174e05277999cb466a094"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "thymeleaf-layout-dialect-3.4.0-sources.jar",
          "url": "thymeleaf-layout-dialect-3.4.0-sources.jar",
          "size": 66549,
          "sha512": "5c4fc16b76a663ea2c0a64837059e287915278cf6885fd8ee07186d78751feeab9e3d8a5ac9be933cc79c9a2490490887672a19d30287f7a5da7c9a9c55563dd",
          "sha256": "829b656ed6b545450a6fd282253ba4a26f8cb27eec3fd8de39db7f1a816be80d",
          "sha1": "1df7068990694ec22020866465acfba902c7f496",
          "md5": "eeac632909717c4e0e9669612493a60f"
        }
      ]
    }
  ]
}
