{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-config",
    "version": "6.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.5.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-6.5.7.jar",
          "url": "spring-security-config-6.5.7.jar",
          "size": 2108136,
          "sha512": "41643285edc4aebb93e76c4c0fd594fdae4d3d942058d50ea42f80ff560e371feb4fd3939d62666aae27aa7b7e7ae3680d153868a6c7e04de0f7f6b486d29bd3",
          "sha256": "6ef5e23054862e4c83f943d6c238bcbe606ea474662fa3afa9b9e3b28788200a",
          "sha1": "7244c8258b5104712cb0be3847ba3753ff80b66e",
          "md5": "b7660e8d30488729c1f41ef6993a3549"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.5.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-6.5.7.jar",
          "url": "spring-security-config-6.5.7.jar",
          "size": 2108136,
          "sha512": "41643285edc4aebb93e76c4c0fd594fdae4d3d942058d50ea42f80ff560e371feb4fd3939d62666aae27aa7b7e7ae3680d153868a6c7e04de0f7f6b486d29bd3",
          "sha256": "6ef5e23054862e4c83f943d6c238bcbe606ea474662fa3afa9b9e3b28788200a",
          "sha1": "7244c8258b5104712cb0be3847ba3753ff80b66e",
          "md5": "b7660e8d30488729c1f41ef6993a3549"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-6.5.7-javadoc.jar",
          "url": "spring-security-config-6.5.7-javadoc.jar",
          "size": 1209396,
          "sha512": "99e39bf2e25529b61d9d26553c9324139cc0e189614bc9c5b49ef09f3d1a7b0ae1be972ed1640965e0e28dc11df723faf3905e7cdec14c076c9bf1210de70967",
          "sha256": "34c973a2d68b7db7c9178d2d229322a29fa162951fac1ec795ead989782b3ec7",
          "sha1": "908a260782aaab6a8c4074c9a50cf5f040017d5a",
          "md5": "e9e76351816730488027df5cfa67c032"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-6.5.7-sources.jar",
          "url": "spring-security-config-6.5.7-sources.jar",
          "size": 1449277,
          "sha512": "10a7b7b4b7aaa5d73a1698e45796b271e6aa1a7f078bf4c7571d13cb9616e49310cb139401bc32394e3ca19a919810924043670edae12c5c68d8da2cc8c9f35e",
          "sha256": "370b7f9ffbb78e7637208b95e68ad0b62ce9d103cb4439d2c7499d26821fb165",
          "sha1": "ecec069a6bb9c19db9cbb674cf55fbf330b36827",
          "md5": "a276a28c6f46c7473d11584f898f224c"
        },
        {
          "name": "spring-security-config-6.5.7-sources.jar",
          "url": "spring-security-config-6.5.7-sources.jar",
          "size": 1449277,
          "sha512": "10a7b7b4b7aaa5d73a1698e45796b271e6aa1a7f078bf4c7571d13cb9616e49310cb139401bc32394e3ca19a919810924043670edae12c5c68d8da2cc8c9f35e",
          "sha256": "370b7f9ffbb78e7637208b95e68ad0b62ce9d103cb4439d2c7499d26821fb165",
          "sha1": "ecec069a6bb9c19db9cbb674cf55fbf330b36827",
          "md5": "a276a28c6f46c7473d11584f898f224c"
        }
      ]
    }
  ]
}
