{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.okhttp3",
    "module": "okhttp",
    "version": "5.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-metadata-5.1.0.jar",
          "url": "okhttp-5.1.0.jar",
          "size": 767,
          "sha512": "165c65503bded11490b09c46935864aa71ee8b9fc4ea1c01e1cb91b209a64af97e92d5d8fd9b4bc78209a8949a79f37ff49edd992171d25ba6f7e0d968cee87c",
          "sha256": "e720a383fdc3eb1df4aac77a085e61b7730837364151de867093fdbcafcb44aa",
          "sha1": "6891a4fd19bcab6f69fe091c2bc6077edec5258e",
          "md5": "7cefaebda364337f3770168187124f31"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "okhttp-kotlin-5.1.0-sources.jar",
          "url": "okhttp-5.1.0-sources.jar",
          "size": 380169,
          "sha512": "62c15e5dad91c68c2e6c8fc9909e6cc5f3528c97b8e88c421404941d1da86f887414349f7d7e448d32baad85252bbc0b5acbc2c47eb370b685af61245a80bd31",
          "sha256": "16b1025e2389e538d4e51afeeb422d956dcf54385e40cf029584ce77b87e0f8e",
          "sha1": "77e418c56edae8a17e141c54c2104fad7f7ad551",
          "md5": "b6bddabb5d257f3418c2e55056ea7428"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../okhttp-android/5.1.0/okhttp-android-5.1.0.module",
        "group": "com.squareup.okhttp3",
        "module": "okhttp-android",
        "version": "5.1.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../okhttp-android/5.1.0/okhttp-android-5.1.0.module",
        "group": "com.squareup.okhttp3",
        "module": "okhttp-android",
        "version": "5.1.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../okhttp-android/5.1.0/okhttp-android-5.1.0.module",
        "group": "com.squareup.okhttp3",
        "module": "okhttp-android",
        "version": "5.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../okhttp-jvm/5.1.0/okhttp-jvm-5.1.0.module",
        "group": "com.squareup.okhttp3",
        "module": "okhttp-jvm",
        "version": "5.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../okhttp-jvm/5.1.0/okhttp-jvm-5.1.0.module",
        "group": "com.squareup.okhttp3",
        "module": "okhttp-jvm",
        "version": "5.1.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../okhttp-jvm/5.1.0/okhttp-jvm-5.1.0.module",
        "group": "com.squareup.okhttp3",
        "module": "okhttp-jvm",
        "version": "5.1.0"
      }
    }
  ]
}
