{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okhttp/5.1.0/okhttp-5.1.0.module",
    "group": "com.squareup.okhttp3",
    "module": "okhttp",
    "version": "5.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-jvm-5.1.0.jar",
          "url": "okhttp-jvm-5.1.0.jar",
          "size": 859817,
          "sha512": "ec41b95bb3a71fde13c51e21cd3b6aee3f93601dd49af533edeab21f71c1a8f0231bfbfee75e223ceba66a02d2f53ab8e4026218efbe9beb9a6c3678588c88cf",
          "sha256": "a6aac7f15d3c2c3cbd2af7ecf56f97407164a604b2db879529950e31cea699b2",
          "sha1": "c17340f19b33c1d28a47b8dc4ae15018aff6dc10",
          "md5": "59087ea3679bc732088588fff8314dbc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-jvm-5.1.0.jar",
          "url": "okhttp-jvm-5.1.0.jar",
          "size": 859817,
          "sha512": "ec41b95bb3a71fde13c51e21cd3b6aee3f93601dd49af533edeab21f71c1a8f0231bfbfee75e223ceba66a02d2f53ab8e4026218efbe9beb9a6c3678588c88cf",
          "sha256": "a6aac7f15d3c2c3cbd2af7ecf56f97407164a604b2db879529950e31cea699b2",
          "sha1": "c17340f19b33c1d28a47b8dc4ae15018aff6dc10",
          "md5": "59087ea3679bc732088588fff8314dbc"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "okhttp-jvm-5.1.0-sources.jar",
          "url": "okhttp-jvm-5.1.0-sources.jar",
          "size": 391572,
          "sha512": "9f3554f63dbcaa427f07d989e6e40e0c500e2e5544ab862b3f94e79b427691d56df31c0246167eb95fdb3273091dbb2619ee0b1215eec3f49f443fe8270cd70f",
          "sha256": "875918275c8e948892d6aa667e36fbfe2c211fe2bf245fb6702b34363df69129",
          "sha1": "041f4ab1dc45e3a2b3db83ca24113fe6a857b364",
          "md5": "ad1cb6a456cca3fcce445963acdcf7b7"
        }
      ]
    }
  ]
}
