{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-crypto",
    "version": "6.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.5.7.jar",
          "url": "spring-security-crypto-6.5.7.jar",
          "size": 104853,
          "sha512": "a53ab04e933f3c8a092c94bec6cf9284bb84020b22d9941bf2c165f241c8e89cfb6d513cb8f9e4af846edaa519534523ee4cd555aff1de14088189b74aa5c6e2",
          "sha256": "ff397e817587bebf70fae924e38d4892f9db11c966f58ce533e2bb8fb7d519da",
          "sha1": "a8b424b612c8103e7c0a5576e2be30d1ac61f38a",
          "md5": "bf371e0764b4192c8535f998066c55df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.5.7.jar",
          "url": "spring-security-crypto-6.5.7.jar",
          "size": 104853,
          "sha512": "a53ab04e933f3c8a092c94bec6cf9284bb84020b22d9941bf2c165f241c8e89cfb6d513cb8f9e4af846edaa519534523ee4cd555aff1de14088189b74aa5c6e2",
          "sha256": "ff397e817587bebf70fae924e38d4892f9db11c966f58ce533e2bb8fb7d519da",
          "sha1": "a8b424b612c8103e7c0a5576e2be30d1ac61f38a",
          "md5": "bf371e0764b4192c8535f998066c55df"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.5.7-javadoc.jar",
          "url": "spring-security-crypto-6.5.7-javadoc.jar",
          "size": 245530,
          "sha512": "ac6025e84433e61b44f9d3c1cb28a9c4881f17e586b1cec70679967684c0768f51134fa07cd0c1683447a3bcdcac562488c3f3a5c7ff668ea55eed36a0109dc1",
          "sha256": "0db4d83011963269bc0214a2304f1265dad2730137b7de1889c1b742e99d51df",
          "sha1": "3ee72bc98aac2cf70fb8e3d47863fa6c445449d0",
          "md5": "20c8638a0e679fc8975d2d63faa5c37b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.5.7-sources.jar",
          "url": "spring-security-crypto-6.5.7-sources.jar",
          "size": 90852,
          "sha512": "897dfde10b0ddf145913651b146f9ec50abe9485cf949cefc73eae9a7c72a4e718ae506afa87ab7e3d688cb2ad9326dd213624cc6c8667636da8dc964f6095ab",
          "sha256": "5a0290703b7f8b07066397c8d58b3186b6afb570e751616a777982e327f0d542",
          "sha1": "b217a457a5744f8133372f71d5069671ef8a29e3",
          "md5": "1a328e2641e0a248cc1ddb14cec19c4e"
        }
      ]
    }
  ]
}
