{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.2.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.15"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.2.15.jar",
          "url": "spring-webmvc-6.2.15.jar",
          "size": 1092647,
          "sha512": "4d60f939fce7eec3bff4114c711852a6ffce8eeba57db8fa05335bb6ee41fab2791d5bc663c58419adff442f406c9374ae2b9859a3bb29516156210d3fc00377",
          "sha256": "118d16bde6ea6aa35c0906d1581c8dea06ddf53668545691f73deed42cb2eacc",
          "sha1": "f290f07e991291b7a67a472ea88d07e9d153c379",
          "md5": "7553277e335714a89ed3f2db5462985d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.15"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.2.15.jar",
          "url": "spring-webmvc-6.2.15.jar",
          "size": 1092647,
          "sha512": "4d60f939fce7eec3bff4114c711852a6ffce8eeba57db8fa05335bb6ee41fab2791d5bc663c58419adff442f406c9374ae2b9859a3bb29516156210d3fc00377",
          "sha256": "118d16bde6ea6aa35c0906d1581c8dea06ddf53668545691f73deed42cb2eacc",
          "sha1": "f290f07e991291b7a67a472ea88d07e9d153c379",
          "md5": "7553277e335714a89ed3f2db5462985d"
        }
      ]
    }
  ]
}
