{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio/3.15.0/okio-3.15.0.module",
    "group": "com.squareup.okio",
    "module": "okio",
    "version": "3.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-3.15.0.jar",
          "url": "okio-jvm-3.15.0.jar",
          "size": 376949,
          "sha512": "f327600f43ab5f56753934848d9f49c3509cc5d4b871271345aa3a457a55bf9e244ff4d7d4e5c3de5eadb024cd2e13aca24817763005ce1b0ef0dc0a06be93dc",
          "sha256": "483dc383b1049d220892322a0d6a4308425f09bb05b48c43d4eaa9ff82b1cd16",
          "sha1": "cb3c285187640f543150fcac1ae012bdd778c0e1",
          "md5": "ea1a1bb6024626d003c1d59ce230926f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-3.15.0.jar",
          "url": "okio-jvm-3.15.0.jar",
          "size": 376949,
          "sha512": "f327600f43ab5f56753934848d9f49c3509cc5d4b871271345aa3a457a55bf9e244ff4d7d4e5c3de5eadb024cd2e13aca24817763005ce1b0ef0dc0a06be93dc",
          "sha256": "483dc383b1049d220892322a0d6a4308425f09bb05b48c43d4eaa9ff82b1cd16",
          "sha1": "cb3c285187640f543150fcac1ae012bdd778c0e1",
          "md5": "ea1a1bb6024626d003c1d59ce230926f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "okio-jvm-3.15.0-sources.jar",
          "url": "okio-jvm-3.15.0-sources.jar",
          "size": 189053,
          "sha512": "919006dc5d0239b67a0425f424808b90a15d94b4c5d6b47df7f29e5632364ef11707045b85259a50b6a4c54a9e4b194c5004f3202293780a1474f39a4970d7d0",
          "sha256": "eca487c49a4905a89556ce413ea198f40f20bb2dc6249d916b3917913bd6dbab",
          "sha1": "ece3f612ebde45c16da7fa5fd69be472d47a266f",
          "md5": "365f6c2890683ae6c29ea027b209882a"
        }
      ]
    }
  ]
}
