{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-web",
    "version": "6.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.5.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-6.5.7.jar",
          "url": "spring-security-web-6.5.7.jar",
          "size": 1052142,
          "sha512": "6ef544de0175691c9b529d9547cc28b23b2ecef082a02bac6c5d7521f8ed12b9df0e342a0bd056a942f96e39450d3fd59ef47a24f17bd2f2cc0fdb964f3c8942",
          "sha256": "1384f07b150de7f5883e90838d256eb01eb54b23082896eccdfe5d02c51bbfdf",
          "sha1": "c3c2f32069fae888d1e5281bd7e0e638f7f6dc26",
          "md5": "825d3fb3d4ad1b0208f39c07e9a6edf9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.5.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-6.5.7.jar",
          "url": "spring-security-web-6.5.7.jar",
          "size": 1052142,
          "sha512": "6ef544de0175691c9b529d9547cc28b23b2ecef082a02bac6c5d7521f8ed12b9df0e342a0bd056a942f96e39450d3fd59ef47a24f17bd2f2cc0fdb964f3c8942",
          "sha256": "1384f07b150de7f5883e90838d256eb01eb54b23082896eccdfe5d02c51bbfdf",
          "sha1": "c3c2f32069fae888d1e5281bd7e0e638f7f6dc26",
          "md5": "825d3fb3d4ad1b0208f39c07e9a6edf9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-6.5.7-javadoc.jar",
          "url": "spring-security-web-6.5.7-javadoc.jar",
          "size": 2300753,
          "sha512": "72faf68bd0debb439e6d7a12c4bdeac77049e9f938f13e1f6ccd6f717977a3df9d53bd3d331b1353c920bbcf6fedb34ca119ab204d535743c3101611bcf88865",
          "sha256": "f6db671e116e16bd8628ea4659d94bc708614b5c0bdfbfc0f5473c4bafb30e99",
          "sha1": "dd7d59597211f01d2359183e435aa06ecc28432b",
          "md5": "6dd5f5f0ca181684a3b502e7d83ff344"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-6.5.7-sources.jar",
          "url": "spring-security-web-6.5.7-sources.jar",
          "size": 867800,
          "sha512": "e5b8a7a052c603877623aa5d6f678fbf311f3a4bb83da3650c5e653e1eb9a2b82cc19bc366eb933f475a5cfffcbe217c58cb68870a1a4f689cd781dbcd51bdbb",
          "sha256": "5a1287755a49b540cb669af0dce24d286d39d69d036d782fad0b582a402289fa",
          "sha1": "267cc2dad036567b7031149bc117ec2c586ede6f",
          "md5": "80ed95c7ded98641bd310ad01ecf0025"
        }
      ]
    }
  ]
}
