{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-beans",
    "version": "6.2.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.15"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-6.2.15.jar",
          "url": "spring-beans-6.2.15.jar",
          "size": 891397,
          "sha512": "a88feade9f1664e723b15fdf55e76e7e66e86033cd0c19d93727e79a831d9a87d5f70315073db40f8f4ad7900c0ae09068f29c10324d4092cf6e50f4d55577a2",
          "sha256": "ffba8542f6799b2afbdcbda715e185cb53bb1d497389ba2102f95088d1564c2c",
          "sha1": "1d0ad7873e865fc9d47c3aac7b7ffb6d0d1500c5",
          "md5": "a8bddadc3bcd6db151275804e6c03af8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.15"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-6.2.15.jar",
          "url": "spring-beans-6.2.15.jar",
          "size": 891397,
          "sha512": "a88feade9f1664e723b15fdf55e76e7e66e86033cd0c19d93727e79a831d9a87d5f70315073db40f8f4ad7900c0ae09068f29c10324d4092cf6e50f4d55577a2",
          "sha256": "ffba8542f6799b2afbdcbda715e185cb53bb1d497389ba2102f95088d1564c2c",
          "sha1": "1d0ad7873e865fc9d47c3aac7b7ffb6d0d1500c5",
          "md5": "a8bddadc3bcd6db151275804e6c03af8"
        }
      ]
    }
  ]
}
