{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.datatype",
    "module": "jackson-datatype-jsr310",
    "version": "2.19.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.19.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.19.4.jar",
          "url": "jackson-datatype-jsr310-2.19.4.jar",
          "size": 136960,
          "sha512": "0d5497a704e5142f711c5ead85ebcd72518528e0a6ff3a31ae8cf886140c30e20be6a947ffc9aec3b2b3e7b168281345944f762d0d6e44a55e75fd21bcc1e4d1",
          "sha256": "070af4d7c345cf975ff783138050678e6194e5bb88ab489385d0311a5fcb1585",
          "sha1": "3cbcf2e636a6b062772299bf19a347536e58c4df",
          "md5": "b85dc514029abd7235fa0cdd7b2c919d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.19.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.19.4.jar",
          "url": "jackson-datatype-jsr310-2.19.4.jar",
          "size": 136960,
          "sha512": "0d5497a704e5142f711c5ead85ebcd72518528e0a6ff3a31ae8cf886140c30e20be6a947ffc9aec3b2b3e7b168281345944f762d0d6e44a55e75fd21bcc1e4d1",
          "sha256": "070af4d7c345cf975ff783138050678e6194e5bb88ab489385d0311a5fcb1585",
          "sha1": "3cbcf2e636a6b062772299bf19a347536e58c4df",
          "md5": "b85dc514029abd7235fa0cdd7b2c919d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.19.4-javadoc.jar",
          "url": "jackson-datatype-jsr310-2.19.4-javadoc.jar",
          "size": 447995,
          "sha512": "f52cf8e821ad1b5bf7e7735758638c434c797b5fb8eb22d88aec37ae42efeab7c7898116d4b691b1d56354332219c644bd08460ca687cb10a6f3250fd7d3d64b",
          "sha256": "20a72e34086a3e5b885eac7c7cebdc7f72b3f48812982638ff62c9e9bc5bcf09",
          "sha1": "20d677cee438ca3482b18b09a800daab30eb8ac0",
          "md5": "c5480b8950e61001522fb35dfd45a3c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.19.4-sources.jar",
          "url": "jackson-datatype-jsr310-2.19.4-sources.jar",
          "size": 92369,
          "sha512": "f6ad08558f3bf2f80a454d5e967afda6fa53f1bfbf7ea19c205dce5aeeb504f481ee1047e0603ac983be34dace57c7a3b383e922cdc8af72b91a286c356878f6",
          "sha256": "7b4baa5a796269d842a94e10cfcb920b4a84b1b53732c58490dfd76812e69509",
          "sha1": "225d239c073ab8ac4ed89188335f94a943645e11",
          "md5": "270441b4228dc48ae4561b0bee468bd8"
        }
      ]
    }
  ]
}
