{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.core",
    "module": "jackson-databind",
    "version": "2.19.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.19.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-databind-2.19.4.jar",
          "url": "jackson-databind-2.19.4.jar",
          "size": 1679441,
          "sha512": "02a80c97ea12874f66802cb2c8909e5358639b41050bd04da495c0ee8db496a0d9d609a3c62a1dca7cbd89681bf340d6f6dbc507d4f21602aa1a7f31b2285ba8",
          "sha256": "b781c431be870deb0bf84421e99e774c256a701f4ba678df80248f55cd16ff74",
          "sha1": "7a39bf9257b726b90b80f27fa3f5174bc75162a5",
          "md5": "11866a41e8db8fc1219fccb98c5ddd38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.19.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-databind-2.19.4.jar",
          "url": "jackson-databind-2.19.4.jar",
          "size": 1679441,
          "sha512": "02a80c97ea12874f66802cb2c8909e5358639b41050bd04da495c0ee8db496a0d9d609a3c62a1dca7cbd89681bf340d6f6dbc507d4f21602aa1a7f31b2285ba8",
          "sha256": "b781c431be870deb0bf84421e99e774c256a701f4ba678df80248f55cd16ff74",
          "sha1": "7a39bf9257b726b90b80f27fa3f5174bc75162a5",
          "md5": "11866a41e8db8fc1219fccb98c5ddd38"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-databind-2.19.4-javadoc.jar",
          "url": "jackson-databind-2.19.4-javadoc.jar",
          "size": 6213024,
          "sha512": "35ed57dff78d04587f409d6c53c6ad0dfa04f9b78810aaacc74b1abce61fe162fdc3d03280cc6dbc0313dca9d02090b2b00a7b8d242d20baf00d3b940750e168",
          "sha256": "e3968d129b031c35deb4d101da605f8ce930677850f5ca62f4c4043431a89f41",
          "sha1": "f814bcacc5d6379b2a0ffd1b35c080e20e6b7c2a",
          "md5": "7aa88c016607c19b9be1c8ba436531ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-databind-2.19.4-sources.jar",
          "url": "jackson-databind-2.19.4-sources.jar",
          "size": 1241899,
          "sha512": "b819facf7645224d384d15cec4f33004f214d29f7a39a1602aa2abce0c7f9b826248b255ae0ae714c29acd750773ea4226b10ae52fdcb58ddd8bbb8037088878",
          "sha256": "4fa122eadae19997aa96d98bcce2e60bd69f5f9382dd1a3e4b740176e3acf1c9",
          "sha1": "7740aa401395fde56531bcbd192d0fea2c3ae039",
          "md5": "8202fed60fa2859ad7f1e11283ca182a"
        }
      ]
    }
  ]
}
